In [91]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeRegressor

In [92]:
df = pd.read_csv("Top Indian Places to Visit.csv")

In [93]:
df

Unnamed: 0      Zone           State         City  \
0             0  Northern           Delhi        Delhi   
1             1  Northern           Delhi        Delhi   
2             2  Northern           Delhi        Delhi   
3             3  Northern           Delhi        Delhi   
4             4  Northern           Delhi        Delhi   
..          ...       ...             ...          ...   
320         320   Western         Gujarat  Gandhinagar   
321         321   Central   Uttar Pradesh         Agra   
322         322   Central  Madhya Pradesh       Bhopal   
323         323  Northern       Rajasthan       Jaipur   
324         324  Northern       Rajasthan       Jaipur   

                             Name          Type Establishment Year  \
0                      India Gate  War Memorial               1921   
1                  Humayun's Tomb          Tomb               1572   
2               Akshardham Temple        Temple               2005   
3            Waste to Wonder Park    Theme Park               2019   
4                   Jantar Mantar   Observatory               1724   
..                            ...           ...                ...   
320                    Akshardham        Temple               1992   
321                     Agra Fort          Fort               1565   
322  Madhya Pradesh Tribal Museum        Museum               2013   
323                   City Palace        Palace               1727   
324            Albert Hall Museum        Museum               1887   

     time needed to visit in hrs  Google review rating  Entrance Fee in INR  \
0                            0.5                   4.6                    0   
1                            2.0                   4.5                   30   
2                            5.0                   4.6                   60   
3                            2.0                   4.1                   50   
4                            2.0                   4.2                   15   
..                           ...                   ...                  ...   
320                          3.0                   4.6                    0   
321                          2.0                   4.5                   40   
322                          2.0                   4.7                   10   
323                          2.0                   4.4                  200   
324                          2.0                   4.5                  200   

    Airport with 50km Radius Weekly Off   Significance DSLR Allowed  \
0                        Yes       None     Historical          Yes   
1                        Yes       None     Historical          Yes   
2                        Yes       None      Religious           No   
3                        Yes     Monday  Environmental          Yes   
4                        Yes       None     Scientific          Yes   
..                       ...        ...            ...          ...   
320                      Yes     Monday      Religious           No   
321                      Yes       None     Historical          Yes   
322                      Yes     Monday       Cultural          Yes   
323                      Yes       None     Historical          Yes   
324                      Yes       None     Historical          Yes   

     Number of google review in lakhs Best Time to visit  
0                                2.60            Evening  
1                                0.40          Afternoon  
2                                0.40          Afternoon  
3                                0.27            Evening  
4                                0.31            Morning  
..                                ...                ...  
320                              0.18                All  
321                              1.30          Afternoon  
322                              0.15                All  
323                              0.51            Morning  
324             

In [94]:
col = ['Type','Google review rating','Number of google review in lakhs','Entrance Fee in INR']
df = df[col]
df

Type  Google review rating  Number of google review in lakhs  \
0    War Memorial                   4.6                              2.60   
1            Tomb                   4.5                              0.40   
2          Temple                   4.6                              0.40   
3      Theme Park                   4.1                              0.27   
4     Observatory                   4.2                              0.31   
..            ...                   ...                               ...   
320        Temple                   4.6                              0.18   
321          Fort                   4.5                              1.30   
322        Museum                   4.7                              0.15   
323        Palace                   4.4                              0.51   
324        Museum                   4.5                              0.63   

     Entrance Fee in INR  
0                      0  
1                     30  
2                     60  
3                     50  
4                     15  
..                   ...  
320                    0  
321                   40  
322                   10  
323                  200  
324                  200  

[325 rows x 4 columns]

In [95]:
df['Entrance Fee in INR'].unique()

array([   0,   30,   60,   50,   15,   35,   20,   80,   70,  500, 1149,
        550,   25, 1150, 2500,   10, 3500,  200, 7500,  350,  300,  100,
         40,  750,   75,  150, 1500,    5,  250,   65,  650, 1100,  890],
      dtype=int64)

In [96]:
df['Entrance Fee in INR'].value_counts()

0       183
50       21
20       19
30       13
10       12
100       8
500       7
40        7
25        6
300       5
15        5
150       4
35        4
200       4
60        4
1149      2
2500      2
80        2
250       2
1500      2
1100      1
650       1
65        1
5         1
3500      1
75        1
750       1
350       1
7500      1
1150      1
550       1
70        1
890       1
Name: Entrance Fee in INR, dtype: int64

In [97]:
df = df[df['Entrance Fee in INR'] != 0]

In [98]:
df['Entrance Fee in INR'].value_counts()

50      21
20      19
30      13
10      12
100      8
40       7
500      7
25       6
15       5
300      5
150      4
60       4
200      4
35       4
2500     2
250      2
1149     2
80       2
1500     2
1100     1
650      1
65       1
5        1
750      1
75       1
1150     1
70       1
350      1
7500     1
550      1
3500     1
890      1
Name: Entrance Fee in INR, dtype: int64

In [99]:
df['Google review rating'] = df['Google review rating'].astype('int64')
df['Number of google review in lakhs'] = df['Number of google review in lakhs'].astype('int64')

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_11392/981051590.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Google review rating'] = df['Google review rating'].astype('int64')
C:\Users\Lenovo\AppData\Local\Temp/ipykernel_11392/981051590.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Number of google review in lakhs'] = df['Number of google review in lakhs'].astype('int64')


In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 1 to 324
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype 
---  ------                            --------------  ----- 
 0   Type                              142 non-null    object
 1   Google review rating              142 non-null    int64 
 2   Number of google review in lakhs  142 non-null    int64 
 3   Entrance Fee in INR               142 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 5.5+ KB


In [101]:
df.shape

(142, 4)

In [102]:
df = pd.get_dummies(df,dtype='int')
df

Google review rating  Number of google review in lakhs  \
1                       4                                 0   
2                       4                                 0   
3                       4                                 0   
4                       4                                 0   
7                       4                                 1   
..                    ...                               ...   
318                     4                                 0   
321                     4                                 1   
322                     4                                 0   
323                     4                                 0   
324                     4                                 0   

     Entrance Fee in INR  Type_Adventure Sport  Type_Amusement Park  \
1                     30                     0                    0   
2                     60                     0                    0   
3                     50                     0                    0   
4                     15                     0                    0   
7                     35                     0                    0   
..                   ...                   ...                  ...   
318                   50                     0                    0   
321                   40                     0                    0   
322                   10                     0                    0   
323                  200                     0                    0   
324                  200                     0                    0   

     Type_Aquarium  Type_Beach  Type_Bird Sanctuary  Type_Botanical Garden  \
1                0           0                    0                      0   
2                0           0                    0                      0   
3                0           0                    0                      0   
4                0           0                    0                      0   
7                0           0                    0                      0   
..             ...         ...                  ...                    ...   
318              0           0                    0                      0   
321              0           0                    0                      0   
322              0           0                    0                      0   
323              0           0                    0                      0   
324              0           0                    0                      0   

     Type_Cave  ...  Type_Temple  Type_Temples  Type_Theme Park  Type_Tomb  \
1            0  ...            0             0                0          1   
2            0  ...            1             0                0          0   
3            0  ...            0             0                1          0   
4            0  ...            0             0                0          0   
7            0  ...            0             0                0          0   
..         ...  ...          ...           ...              ...        ...   
318          0  ...            0             0                0          0   
321          0  ...            0             0                0          0   
322          0  ...            0             0                0          0   
323          0  ...            0             0                0          0   
324          0  ...            0             0                0          0   

     Type_Tombs  Type_Valley  Type_Vineyard  Type_Waterfall  \
1             0            0              0               0   
2             0            0              0               0   
3             0            0              0               0   
4             0            0              0               0   
7             0            0              0               0   
..          ...          ...            ...             ...   
318           0            0              0               0   
321           0  

In [103]:
X = df.drop(columns = ['Entrance Fee in INR'])
Y = df['Entrance Fee in INR']

In [104]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [105]:
X_train.shape

(99, 46)

In [106]:
model_lin = LinearRegression()
model_lin.fit(X_train,Y_train)

LinearRegression()

In [107]:
model_lin.predict(X_test)

array([ 1.15264374e+02,  3.10692139e+01, -1.96575970e+15,  1.32984985e+02,
        7.74645996e+01, -3.88803406e+01,  1.08613556e+02,  3.80964661e+01,
        1.08613556e+02,  2.53085703e+11,  7.74645996e+01,  2.34608984e+14,
        7.74645996e+01,  9.24087483e+13,  3.60155334e+01,  1.47199860e+13,
        8.89801788e+02,  7.74645996e+01, -3.88803406e+01,  8.89801788e+02,
        2.86602478e+01,  1.18030701e+01,  1.01848053e+02,  3.60155334e+01,
        5.84400024e+01, -9.57858485e+15,  7.74645996e+01,  2.03001282e+02,
        1.32984985e+02,  4.74530334e+01, -2.34909313e+14,  1.32984985e+02,
       -1.54325935e+14, -7.35198364e+01,  3.57602722e+02, -4.22878076e+14,
        2.03001282e+02,  1.61659760e+02,  1.32984985e+02,  2.00619507e+01,
       -6.26361694e+01,  7.74645996e+01,  2.86602478e+01])

In [108]:
model_lin.score(X_train,Y_train)

0.9244850092954612

In [109]:
model_lin.score(X_test,Y_test)

-1.4327625119514597e+24

In [110]:
model_las = Lasso(alpha = 0.001,max_iter = 1,tol=0.00001)
model_las.fit(X_train,Y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 789007.4614403895, tolerance: 172.1558583838384
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=0.001, max_iter=1, tol=1e-05)

In [111]:
model_las.predict(X_test)

array([  94.44265619,   32.3968413 ,  154.95128566,  130.5037887 ,
        101.11146365, -286.78077557,  108.72570784,   36.73947114,
        108.72570784,  154.95128566,  101.11146365,  484.53392368,
        101.11146365,  154.95128566,   20.16598956,  154.95128566,
        526.54014345,  101.11146365, -286.78077557,  526.54014345,
         24.19521456,   18.79716382,  108.55300891,   20.16598956,
         59.18316667,  154.95128566,  101.11146365,  211.42185754,
        130.5037887 ,   42.80186245, -326.05107082,  130.5037887 ,
        154.95128566, -111.06619298,  373.27017737,  154.95128566,
        211.42185754,  163.15727854,  130.5037887 ,   20.87143398,
        -99.76732193,  101.11146365,   24.19521456])

In [112]:
model_las.score(X_train,Y_train)

0.9084527008423958

In [113]:
model_las.score(X_test,Y_test)

-0.07123722085794904

In [114]:
model_rid = Ridge(alpha = 0.0000001,max_iter = 1,tol=1000)
model_rid.fit(X_train,Y_train)

Ridge(alpha=1e-07, max_iter=1, tol=1000)

In [115]:
model_rid.score(X_train,Y_train)

0.9244889093413742

In [116]:
model_rid.score(X_test,Y_test)

-0.046832741994165206

In [117]:
model_tree = DecisionTreeRegressor()
model_tree.fit(X_train,Y_train)

DecisionTreeRegressor()

In [118]:
model_tree.predict(X_test)

array([163.75      ,  49.        ,  20.        , 133.        ,
        59.        ,  50.        , 108.75      ,  38.33333333,
       108.75      ,  20.        ,  59.        ,  20.        ,
        59.        ,  20.        ,  35.        ,  20.        ,
       890.        ,  59.        ,  50.        , 890.        ,
        30.        ,  10.        , 100.        ,  35.        ,
        59.16666667,  20.        ,  59.        , 233.75      ,
       133.        ,  50.        ,  20.        , 133.        ,
        20.        ,  20.        , 350.        ,  20.        ,
       233.75      , 163.75      , 133.        ,  20.        ,
        30.        ,  59.        ,  30.        ])

In [119]:
model_tree.score(X_train,Y_train)

0.9258676839707356

In [120]:
model_tree.score(X_test,Y_test)

-0.04910939927970692